version: "3"
services:
  community-mysql:
    image: mysql:5.7
    container_name: community-mysql
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password # root 비밀번호 설정
      MYSQL_DATABASE: your_database_name # 초기 생성할 데이터베이스 설정
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
